### ISSUE TITLE
Error thrown with Anki 2.1.21 beta 2

### ISSUE THREAD

**Issue by Cupbox** [ijgnd/anki21__browser_card_info_bar#4]
Debug info:
Anki 2.1.21 (65ec9d19) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-02-25 07:37:01

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 76, in handler
  File "aqt\browser.py", line 854, in <lambda>
  File "aqt\browser.py", line 873, in _onRowChanged
  File "aqt\gui_hooks.py", line 174, in __call__
  File "lib\site-packages\anki\hooks.py", line 555, in runHook
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\2140680811\infobar.py", line 126, in updateInfoBar
    updateInfoBar_default(self)
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\2140680811\infobar.py", line 147, in updateInfoBar_default
    p = self.cardstats(self.card)
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\2140680811\card_properties.py", line 52, in cardstats
    o["Interval"]     = fmt(card.ivl * 86400) if card.queue == 2 else ""
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\2140680811\card_properties.py", line 25, in <lambda>
    fmt = lambda x, **kwargs: fmtTimeSpan(x, short=True, **kwargs)
TypeError: fmtTimeSpan() got an unexpected keyword argument 'short'

**Comment by Cupbox** [comment]
Working as of beta 3
